training_pipeline_config:
  pipeline_name: stockify
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/ArshadManer/stock_data/main/Stock_data.zip
  # dataset_download_url: https://raw.githubusercontent.com/pratikshinde115/data/main/data.zip
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 



data_validation_config:
  schema_dir: config
  report_file_name: report.json
  report_page_file_name: report.html

data_transformation_config:
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  
model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.h5
  base_accuracy: 0.3
  model_config_dir: config
  model_config_file_name: model.yaml


model_evaluation_config:
  model_evaluation_file_name: model_evaluation.yaml
  

model_pusher_config:
  model_export_dir: saved_models